### ISSUE TITLE
Wallet address cached

### ISSUE THREAD

**Issue by gerbz** [devdotxyz/eth-xyz#101]
Updated the ETH wallet address record on ENS, yet I can't get it to update at eth.xyz.  Maybe a query parameter I can add to the URL or API endpoint to skip the cache?

**Comment by gerbz** [comment]
Refreshed after 48 minutes, but would still be nice to trigger a refresh manually.

**Comment by jhxyz** [comment]
Hi @gerbz - wanted to let you know that we have now added a "Refresh Records" button on the profile that will bust the cache manually! Thank you for the query parameter idea as well.
