### ISSUE TITLE
investigate non-Ethereum cryptocurrency addresses

### ISSUE THREAD

**Issue by jhxyz** [devdotxyz/eth-xyz#173]
It was reported by a user that non-Ethereum cryptocurrency addresses are not displaying correctly, and instead are being reformatted into the Ethereum hash pattern.

Look into & fix if possible.

**Comment by jayson687** [comment]
Always getting weekly 30,000 US $ from this hacker and their bank transfers are safe, fast and same day delivery contact via: d a r k w e b p r o g r a m m e r @ g m a i l . c o m

**Comment by jhxyz** [comment]
This is currently blocked as the related addresses appear to come formatted like this from a 3rd party API, we are not formatting it this way ourselves.
