### ISSUE TITLE
Support .eth subdomains (SSL issue)

### ISSUE THREAD

**Issue by jhxyz** [devdotxyz/eth-xyz#32]
Right now eth.xyz can only support .eth subdomains via this method: eth.xyz/sub.domain

Ideally it would support .eth subdomains in the short link like this: sub.domain.eth.xyz

We are currently using Amazon SSL which does not support wildcard 4th level domains.

Feedback from user:

having http://subdomain.name.eth.xyz work would be cool; not sure how you guys built it, but it should be doable using some dns-fu magic.

Eg if you're building the corollary to family sharing, you end up with:

smith.eth
dad.smith.eth
mom.smith.eth
kid.smith.eth
...
etc.

Adam

**Comment by genxyzteam** [comment]
Occam's Razor applied... redirected http subdomains to their https equivalents

i.e. http://vault.cooperray.eth.xyz resolves to https://eth.xyz/vault.cooperray.eth

**Comment by jhxyz** [comment]
Occam's Razor applied... redirected http subdomains to their https equivalents

i.e. http://vault.cooperray.eth.xyz/ resolves to https://eth.xyz/vault.cooperray.eth

**Comment by jhxyz** [comment]
Occam's Razor applied... redirected http subdomains to their https equivalents

i.e. http://vault.cooperray.eth.xyz/ resolves to https://eth.xyz/vault.cooperray.eth
