### ISSUE TITLE
XSS due to the lack of the ENS names sanitization

### ISSUE THREAD

**Issue by Raz0r** [devdotxyz/eth-xyz#37]
Hi!

ENS names are inserted into DOM without sanitization which leads to Cross-Site Scripting.

<img width="1522" alt="Снимок экрана 2021-12-22 в 14 20 14" src="https://user-images.githubusercontent.com/150087/147085147-360a4d76-f6d9-410b-86ee-ac68151d3bc0.png">

See also: https://twitter.com/theRaz0r/status/1456247675775594504?s=20

**Comment by jhxyz** [comment]
Thank you for reporting! On it

**Comment by brendandebeasi** [comment]
Great find @Raz0r, we patched this. Cheers!
