### ISSUE TITLE
Need ability to truly 'hide' hidden NFTs

### ISSUE THREAD

**Issue by cmotiff** [devdotxyz/eth-xyz#71]
What's the point of using the eth.xyz if it's filled with spam/unwanted NFTs? If it's a problem with Opensea, can the devs reach out and see if the API can be altered to discern what's hidden? People have been having this same problem for months

**Comment by genteamxyz** [comment]
Hello, we have reached out but have not heard back! OS does not provide the hidden flag in their API. We need help from the community to bring this to their attention.

**Comment by jhxyz** [comment]
OpenSea API V2 was finally considered stable in October 2023, and Eth.xyz was updated Nov 2023.
NFTs hidden on OpenSea profiles will no longer proliferate into Eth.xyz profiles.
https://docs.opensea.io/changelog/api-v2-fully-supported
